config/routes.rb
Dealmap::Application.routes.draw do

  resources :images

  
  resources :tags

  get "sessions/new"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  match '/about',   :to => 'pages#about'
  match '/privacy',    :to => 'pages#privacy'
  
  get "deals/import"
  match '/deals/upload' => 'deals#upload'
  resources :deal_locations
  
  resources :deal_locations do 
    member do
      post 'new'
    end
  end
  resources :searches

  resources :sale_details

  resources :sales

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'deals#index'

  resources :deals
  
  resources :deals do
    member do
      post 'print'
    end
  end
  resources :user_types

  resources :categories
  
  match '/sales/new/deals/:deal_id' => 'sales#new'
  
  match '/deals/:deal_id/print' => 'deals#print'
  
  match '/get_deals_within_bounds' => 'deals#get_deals_within_bounds'
  match '/get_deal' => 'deals#get_deal'
  match '/get_deals_for_view' => 'deals#get_deals_for_view'
    
  get 'scrape/scrape_schedule'
  get 'scrape/scrape_site'
  

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  set_primary_keys :sales_id

#  has_many :sale_details
#  has_many :deals, :through => :sale_details
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_filter :authenticate
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @deal = Deal.find(params[:deal_id])
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
      format.json { render json: @deal }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @deal = Deal.find(params[:deal][:deal_id]);
    
    
    
    sale_hash = {
      :purchase_date => DateTime.now,
      :total_amount => (@deal.price.to_f * params[:sale]['quantity'].to_f),
      :user_id => current_user.id,
      :quantity => params[:sale][:quantity]
    }
    @sale = Sale.new(sale_hash)
    
    success = nil;
    
    ActiveRecord::Base.transaction do
      success = @sale.save
      
      sale_detail = SaleDetail.new( { :sale_id => @sale.id , :deal_id => @deal.id } )
      
      success = success && sale_detail.save
    end

    respond_to do |format|
      if success
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% @sale.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <br/><br/>
  
  <%=  hidden_field(:deal, :deal_id)%>

  <div class="actions">
    <%= f.submit %>
  </div>


  <br/><br/>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <tr>
    <th>Purchase date</th>
    <th>Total amount</th>
    <th>Quantity</th>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.purchase_date %></td>
    <td><%= sale.total_amount %></td>
    <td><%= sale.quantity %></td>
    <td><%= sale.status %></td>
    <td><%= sale.user_id %></td>
    <td><%= link_to 'Show', sale %></td>
    <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td><%= link_to 'Destroy', sale, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>
Price per Unit: <%= ActiveRecordHelper.round_to_decimal @deal.price, 2 %>
<br/><br/>
Available: <%= @deal.quantity %>
<br/><br/>
<%= render 'form' %>

<%= link_to 'Back', sales_path %>
<br/><br/>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Purchase date:</b>
  <%= @sale.purchase_date %>
</p>

<p>
  <b>Total amount:</b>
  <%= @sale.total_amount %>
</p>

<p>
  <b>Quantity:</b>
  <%= @sale.quantity %>
</p>

<p>
  <b>Status:</b>
  <%= @sale.status %>
</p>

<p>
  <b>User:</b>
  <%= @sale.user_id %>
</p>


<%= link_to 'Back', deals_path %>