config/routes.rb
Dealmap::Application.routes.draw do

  resources :images

  
  resources :tags

  get "sessions/new"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  match '/about',   :to => 'pages#about'
  match '/privacy',    :to => 'pages#privacy'
  
  get "deals/import"
  match '/deals/upload' => 'deals#upload'
  resources :deal_locations
  
  resources :deal_locations do 
    member do
      post 'new'
    end
  end
  resources :searches

  resources :sale_details

  resources :sales

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'deals#index'

  resources :deals
  
  resources :deals do
    member do
      post 'print'
    end
  end
  resources :user_types

  resources :categories
  
  match '/sales/new/deals/:deal_id' => 'sales#new'
  
  match '/deals/:deal_id/print' => 'deals#print'
  
  match '/get_deals_within_bounds' => 'deals#get_deals_within_bounds'
  match '/get_deal' => 'deals#get_deal'
  match '/get_deals_for_view' => 'deals#get_deals_for_view'
    
  get 'scrape/scrape_schedule'
  get 'scrape/scrape_site'
  

end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  set_primary_keys :deal_id , :sale_id
  
#  belongs_to :deal
#  belongs_to :sale 
  
end

app/controllers/sale_details_controller.rb
class SaleDetailsController < ApplicationController
  before_filter :authenticate
  # GET /sale_details
  # GET /sale_details.json
  def index
    @sale_details = SaleDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sale_details }
    end
  end

  # GET /sale_details/1
  # GET /sale_details/1.json
  def show
    @sale_detail = SaleDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale_detail }
    end
  end

  # GET /sale_details/new
  # GET /sale_details/new.json
  def new
    @sale_detail = SaleDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale_detail }
    end
  end

  # GET /sale_details/1/edit
  def edit
    @sale_detail = SaleDetail.find(params[:id])
  end

  # POST /sale_details
  # POST /sale_details.json
  def create
    @sale_detail = SaleDetail.new(params[:sale_detail])

    respond_to do |format|
      if @sale_detail.save
        format.html { redirect_to @sale_detail, notice: 'Sale detail was successfully created.' }
        format.json { render json: @sale_detail, status: :created, location: @sale_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @sale_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sale_details/1
  # PUT /sale_details/1.json
  def update
    @sale_detail = SaleDetail.find(params[:id])

    respond_to do |format|
      if @sale_detail.update_attributes(params[:sale_detail])
        format.html { redirect_to @sale_detail, notice: 'Sale detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_details/1
  # DELETE /sale_details/1.json
  def destroy
    @sale_detail = SaleDetail.find(params[:id])
    @sale_detail.destroy

    respond_to do |format|
      format.html { redirect_to sale_details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/views/sale_details/_form.html.erb
<%= form_for(@sale_detail) do |f| %>
  <% if @sale_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale_detail.errors.count, "error") %> prohibited this sale_detail from being saved:</h2>

      <ul>
      <% @sale_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sale_id %><br />
    <%= f.number_field :sale_id %>
  </div>
  <div class="field">
    <%= f.label :deal_id %><br />
    <%= f.number_field :deal_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sale_details/edit.html.erb
<h1>Editing sale_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_detail %> |
<%= link_to 'Back', sale_details_path %>

app/views/sale_details/index.html.erb
<h1>Listing sale_details</h1>

<table>
  <tr>
    <th>Sale</th>
    <th>Deal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sale_details.each do |sale_detail| %>
  <tr>
    <td><%= sale_detail.sale_id %></td>
    <td><%= sale_detail.deal_id %></td>
    <td><%= link_to 'Show', sale_detail %></td>
    <td><%= link_to 'Edit', edit_sale_detail_path(sale_detail) %></td>
    <td><%= link_to 'Destroy', sale_detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale detail', new_sale_detail_path %>

app/views/sale_details/new.html.erb
<h1>New sale_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_details_path %>

app/views/sale_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sale:</b>
  <%= @sale_detail.sale_id %>
</p>

<p>
  <b>Deal:</b>
  <%= @sale_detail.deal_id %>
</p>


<%= link_to 'Edit', edit_sale_detail_path(@sale_detail) %> |
<%= link_to 'Back', sale_details_path %>